feat: Configure Kubernetes

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -22,3 +22,12 @@ jobs:
           --password-stdin ghcr.io
       - name: Publish container
         run: docker push ghcr.io/kuzznya/timepicker/frontend --all-tags
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Prepare .kube directory
+        run: mkdir ~/.kube || echo "Cannot create ~/.kube directory, skipping"
+      - name: Prepare kubeconfig
+        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
+      - name: Deploy to Kubernetes
+        run: kubectl rollout restart deployment frontend --namespace master
diff --git a/.github/workflows/websocket-service.yml b/.github/workflows/websocket-service.yml
--- a/.github/workflows/websocket-service.yml
+++ b/.github/workflows/websocket-service.yml
@@ -20,3 +20,12 @@ jobs:
         env:
           DOCKER_USERNAME: ${{ github.actor }}
           DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Prepare .kube directory
+        run: mkdir ~/.kube || echo "Cannot create ~/.kube directory, skipping"
+      - name: Prepare kubeconfig
+        run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
+      - name: Deploy to Kubernetes
+        run: kubectl rollout restart deployment websocket-service --namespace master
